name: clean_architecture_block
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.0.15
  mockito: ^5.3.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

